#!/bin/bash
chmod u+x *
git add .
git commit -m "0x03. Shell, init files, variables and expansions"
git push "https://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@github.com/mo1699/alx-system_engineering-devops.git"
